name: gh-release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: pull-sc-machine-image
        run: docker pull ostis/sc-machine:0.7.0-Rebirth

      - name: install
        run: yarn install

      - name: run test
        run: |
          sudo docker run --rm -i -p 8090:8090 ostis/sc-machine:0.7.0-Rebirth serve &
          yarn run test-machine

  gh-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: read changelog
        id: changelogReader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.ref_name }}
          path: docs/changelog.md

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelogReader.outputs.changes }}
          name: '${{ github.ref_name }}'
