name: pull-request-ci

on:
  pull_request:
    branches: [ develop, main, release/** ]

jobs:
  check-pr-commits:
    name: Check commit messages
    runs-on: ubuntu-20.04

    steps:
      - name: GS Commit Message Checker
        uses: GsActions/commit-message-checker@v1
        with:
          # A regex pattern to check if a commit message is valid.
          pattern: "((feat|fix|docs|style|refactor|test|build|ci|perf)+(\\([a-z]+(.)+\\))?\\: [a-z]+(.)+)|(Review fixes(.)*)|(Merge pull request(.)*)"
          # Expression flags change how the expression is interpreted.
          flags: # optional, default is gm
          # A error message which will be returned in case of an error.
          error: "One of commit messages has an incorrect title. Please read the documentation: docs/dev/pr.md"
          # Setting this input to true will exclude the Pull Request title from the check.
          excludeTitle: true # optional, default is false
          # Setting this input to true will exclude the Pull Request description from the check.
          excludeDescription: true # optional, default is false
          # Setting this input to true will check all Pull Request commits
          checkAllCommitMessages: true # optional, default is false
          # you must provide GITHUB_TOKEN to this input if checkAllCommitMessages is true
          accessToken: ${{ secrets.GITHUB_TOKEN }} # optional, default is false

  build:
    name: build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: npm install

      - name: build
        run: npm run build
